name: Tex Whitney Productions
favicon: null
layout_spectrum: 1
typography_spectrum: 0.67766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.0011301962658762932
  lightness: 0.8777369579765946
  saturation: 0.784788137068972
  rhythmicContrast: 0.4342812751419842
purpose: []
