name: Tex Whitney Productions
favicon: null
layout_spectrum: 0.91103
typography_spectrum: 0.67766
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1d1911'
    - '#494236'
    - '#dcd9d4'
    - '#827b6f'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
